### PR TITLE
check if debase installed (already_installed doesn't work)

### PR DESCRIPTION
**Pull request by ViugiNick**

### CODE REVIEW

**Comment by alflanagan** [comment]
Has anybody looked at this? It seems to solve a common install problem, it seems a fix would be a high priority.

**Comment by ViugiNick** [comment]
> Has anybody looked at this? It seems to solve a common install problem, it seems a fix would be a high priority.

Do you have a problem with offline installation or what kind of install problem?

**Comment by alflanagan** [comment]
I've created a rails project with `rails new ...`, then used `bundle add --group=development ruby-debug-ide`. This is an online installation. When I try to debug some ruby code in VS Code, I get
```
Uncaught exception: cannot load such file -- debase
	/home/aflanagan/Devel/ruby/fred/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
	/home/aflanagan/Devel/ruby/fred/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	/home/aflanagan/Devel/ruby/fred/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	/home/aflanagan/Devel/ruby/fred/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	/home/aflanagan/Devel/ruby/fred/vendor/bundle/ruby/2.5.0/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:9:in `<main>'
	/home/aflanagan/Devel/ruby/fred/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
```

So `bundle add --group=development debase` solves the problem, it just seems like that shouldn't be necessary.

```
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
$ rails -v
Rails 5.2.3
```

**Comment by ViugiNick** [comment]
@alflanagan Can you attach your `gem list` result please?

**Comment by deivid-rodriguez** [comment]
Hi!

We have removed `Gem::DependencyInstaller#find_gems_with_sources` from current rubygems master, so installation of `ruby-debug-ide` will be broken in the next rubygems release.

We don't want to break it, so I'll be reverting the removal, but we don't expect this method to be used by extensions, and on top of that, this PR is correct. `Gem::DependencyInstaller#find_gems_with_sources` uses `Gem::Source::Local` under the hood which look for gems in the CWD. So this check always returns `false` at the moment and the `debase` gem is always reinstalled.

The correct solution to do what you want is what this PR is proposing (`dep.matching_specs.none?`), but if you're ready to drop support for ruby 1.8 and ruby 1.9, the most correct and supported solution would be to remove the extension and add `debase` as a runtime dependency of `ruby-debug-ide`.

**Comment by deivid-rodriguez** [comment]
Also, the latter option I proposed would fix issues like #92 or #187.

**Comment by deivid-rodriguez** [comment]
@ViugiNick I'm happy to create a rebased version of this PR in case it helps moving it forward.

**Comment by ViugiNick** [comment]
@ViugiNick We are not ready to drop support of 1.8 and 1.9 ruby versions. Am I right, that then changes, purposed in this PR will fix the problem?

**Comment by deivid-rodriguez** [comment]
Thank you @ViugiNick!

**Comment by stanhu** [comment]
Thanks, this solved my problem. I checked out the `v0.7.0` tag, picked this commit, built the gem, and installed it so that my dependency worked. Would someone mind releasing a new version?

**Comment by ViugiNick** [comment]
@stanhu done

**Comment by stanhu** [comment]
Thank you!

**Pull request merged**
